// MongoDB Seed Script
// Usage: node dist/scripts/seed.js

require('dotenv').config({ path: require('path').resolve(__dirname, '../../.env') }); // Adjust path as needed
const { MongoClient, ObjectId } = require('mongodb');

const MONGODB_URI = process.env.MONGODB_URI;
if (!MONGODB_URI) {
  console.error("Error: MONGODB_URI is not defined in .env file.");
  process.exit(1);
}

const client = new MongoClient(MONGODB_URI);

async function seedData() {
  try {
    await client.connect();
    console.log("Connected to MongoDB.");
    const db = client.db(); // Use default DB from connection string

    // 1. Seed Skill Pack Contents
    const skillPackContentsCollection = db.collection('skill_pack_contents');
    await skillPackContentsCollection.deleteMany({}); // Clear existing data

    const sampleSkillPacks = [
      {
        // This skill_pack_id should correspond to a skill_pack in PostgreSQL
        // For seeding, you might need to predefine some UUIDs or fetch them after seeding PG
        skill_pack_pg_id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11", // Example UUID
        content: {
          instructions: "This skill pack helps write Python code efficiently.",
          examples: [
            { input: "Create a function to add two numbers.", output: "def add(a, b):\n  return a + b" },
            { input: "How to read a file in Python?", output: "with open('file.txt', 'r') as f:\n  content = f.read()" }
          ],
          templates: [
            { name: "Basic Flask App", code: "from flask import Flask\napp = Flask(__name__)\n\n@app.route('/')\ndef hello():\n  return 'Hello, World!'" }
          ],
          knowledge_base_summary: "Contains common Python syntax, standard library usage, and best practices.",
          prompt_templates: [
            { name: "Code Generation", template: "Generate Python code for the following task: {{task_description}}." },
            { name: "Code Explanation", template: "Explain this Python code snippet: {{code_snippet}}." }
          ]
        },
        version: "1.0.0",
        // embeddings: [], // To be generated by a task
        // chunk_metadata: {}, // Metadata for vector search chunks
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        skill_pack_pg_id: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a12", // Example UUID
        content: {
          instructions: "This skill pack assists with creative writing, such as stories and poems.",
          examples: [
            { input: "Write a short poem about the moon.", output: "Silver disc in velvet night,\nGuiding stars with gentle light." },
          ],
          knowledge_base_summary: "Includes information on literary devices, story structures, and poetic forms.",
          prompt_templates: [
            { name: "Story Idea", template: "Generate a story idea based on the following theme: {{theme}}." },
          ]
        },
        version: "1.0.0",
        created_at: new Date(),
        updated_at: new Date()
      }
    ];
    const resultContents = await skillPackContentsCollection.insertMany(sampleSkillPacks);
    console.log(`${resultContents.insertedCount} skill pack contents seeded.`);

    // 2. Seed System Configurations
    const systemConfigsCollection = db.collection('system_configurations');
    await systemConfigsCollection.deleteMany({});

    const systemConfigs = [
      {
        key: "default_ai_model",
        value: "gpt-3.5-turbo",
        description: "Default AI model to use for general tasks.",
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        key: "max_tokens_per_response",
        value: 2048,
        description: "Maximum number of tokens allowed in a single AI response.",
        created_at: new Date(),
        updated_at: new Date()
      },
      {
        key: "embedding_model",
        value: "text-embedding-ada-002",
        description: "Default model for generating text embeddings.",
        created_at: new Date(),
        updated_at: new Date()
      }
    ];
    const resultConfigs = await systemConfigsCollection.insertMany(systemConfigs);
    console.log(`${resultConfigs.insertedCount} system configurations seeded.`);

    console.log("Database seeding completed successfully.");

  } catch (err) {
    console.error("Error during database seeding:", err);
    process.exit(1);
  } finally {
    await client.close();
    console.log("MongoDB connection closed.");
  }
}

seedData();
